services:
  mysql:
    image: mysql:9.3.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - ${DATABASE_PORT}:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./data/${PROJECT_NAME}/mysql:/var/lib/mysql:cached