services:
  nginx:
    build:
      context: ./nginx
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ${PROJECT_DIRECTORY}:/var/www/html:cached
      - ./nginx/conf.d:/etc/nginx/conf.d
    container_name: ${PROJECT_NAME}-nginx